services:

  backend:
    build:
      context: ../..
      dockerfile: DevOps/docker/Dockerfile.backend

  frontend:
    build:
      context: ../..
      dockerfile: DevOps/docker/Dockerfile.react

  dashboard:
    build:
      context: ../..
      dockerfile: DevOps/docker/Dockerfile.angular