# Use the official Node.js 22 LTS Alpine image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY tripper_backend_api/package*.json ./

# Install project dependencies
RUN npm ci

# Copy the application source code
COPY tripper_backend_api .

# Expose the application port
EXPOSE 4000

# Start the Node.js application
CMD ["npm", "start"]