name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tripper_backend_api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      # - name: Run Tests
      #   run: npm test

      - name: Build Docker Image
        run: |
          docker build \
          -f ../DevOps/docker/Dockerfile.backend \
          -t tripper-backend ..